Lmyc/Models/Document.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lmyc.Models
{
    public class Document
    {
        [Key]
        public int DocumentId { get; set; }

        [Display(Name ="DocumentName")]
        public string DocumentName { get; set; }

        [NotMapped]
        public IFormFile FileToUpload { get; set; }

        [Display(Name = "Link")]
        public string Path { get; set; }

        [Display(Name = "Created By")]
        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }
    }
}

Lmyc/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lmyc.Data;
using Lmyc.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Lmyc.Controllers
{
    [Authorize (Policy = "RequireAdmin")]
    public class DocumentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DocumentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Documents
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Document.Include(d => d.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Documents/Details/5
        public ActionResult Details(string path)
        {
            string contentType = GetContentType(path);
            if (contentType.Equals("abort"))
            {
                return RedirectToAction(nameof(Index));
            }
            FileStream stream;
            try
            {
                stream = new FileStream(@path, FileMode.Open);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Index));
            }

            return new FileStreamResult(stream, contentType);
        }

        // GET: Documents/Create
        public async Task<IActionResult> Create()
        {
            ViewData["UserId"] = (await _userManager.GetUserAsync(User)).Id;
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DocumentId,UserId")] Document document, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file == null || file.Length == 0)
                    return Content("file not selected");

                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/documents",
                            file.FileName.Trim());

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                document.DocumentName = file.FileName.Trim();
                document.Path = "wwwroot/documents/"+file.FileName;
                _context.Add(document);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = (await _userManager.GetUserAsync(User)).Id;
            return View(document);
        }

        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .Include(d => d.User)
                .SingleOrDefaultAsync(m => m.DocumentId == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var document = await _context.Document.SingleOrDefaultAsync(m => m.DocumentId == id);

            FileInfo file = new FileInfo(document.Path);
            if(file.Exists)
            {
                file.Delete();
            }
            
            _context.Document.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocumentExists(int id)
        {
            return _context.Document.Any(e => e.DocumentId == id);
        }

        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename not present");

            var path = Path.Combine(
                           Directory.GetCurrentDirectory(),
                           "wwwroot/documents", filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            if(!types.ContainsKey(ext))
            {
                return "abort";
            }
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }
    }
}

Lmyc/Views/Documents/Create.cshtml
@model Lmyc.Models.Document

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Document</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Documents" asp-action="Create" method="post" enctype="multipart/form-data">
            <input type="hidden" value="@ViewBag.UserId" asp-for="UserId"/>
            <input type="file" name="file" accept=".txt,.pdf,.csv"/>
            <button type="submit">Upload File</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Lmyc/Views/Documents/Delete.cshtml
@model Lmyc.Models.Document

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Document</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DocumentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DocumentId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lmyc/Views/Documents/Details.cshtml
@model Lmyc.Models.Document

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Document</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DocumentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DocumentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lmyc/Views/Documents/Index.cshtml
@model IEnumerable<Lmyc.Models.Document>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DocumentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                Download
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                <a asp-action="Details" asp-route-path="@item.Path">View</a>
            </td>
            <td>
                <a asp-action="Download" asp-route-filename="@item.DocumentName">Download</a>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.DocumentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>