Lmyc/Controllers/BoatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lmyc.Data;
using Lmyc.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Lmyc.Controllers
{
    public class BoatsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BoatsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Boats
        public async Task<IActionResult> Index()
        {
            return View(await _context.Boats.ToListAsync());
        }

        // GET: Boats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats
                .SingleOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // GET: Boats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoatId,BoatName,BoatStatus,BoatPicture,BoatDescription,BoatLength,BoatMake,BoatYear,CreditsPerHourOfUsage")] Boat boat, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    if (Image.Length > 0)
                    //Convert Image to byte and save to database
                    {
                        byte[] imageBytes = null;
                        using (var fs = Image.OpenReadStream())
                        using (var ms = new MemoryStream())
                        {
                            fs.CopyTo(ms);
                            imageBytes = ms.ToArray();
                        }
                        boat.BoatPicture = imageBytes;
                    }
                }
                _context.Add(boat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boat);
        }

        // GET: Boats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats.SingleOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }
            return View(boat);
        }

        // POST: Boats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoatId,BoatName,BoatStatus,BoatPicture,BoatDescription,BoatLength,BoatMake,BoatYear,CreditsPerHourOfUsage")] Boat boat, IFormFile Image)
        {
            if (id != boat.BoatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Image != null)
                {
                    if (Image.Length > 0)
                    //Convert Image to byte and save to database
                    {
                        byte[] imageBytes = null;
                        using (var fs = Image.OpenReadStream())
                        using (var ms = new MemoryStream())
                        {
                            fs.CopyTo(ms);
                            imageBytes = ms.ToArray();
                        }
                        boat.BoatPicture = imageBytes;
                    }
                }
                try
                {
                    _context.Update(boat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoatExists(boat.BoatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boat);
        }

        // GET: Boats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boats
                .SingleOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // POST: Boats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boat = await _context.Boats.SingleOrDefaultAsync(m => m.BoatId == id);
            _context.Boats.Remove(boat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoatExists(int id)
        {
            return _context.Boats.Any(e => e.BoatId == id);
        }
    }
}

Lmyc/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lmyc.Data;
using Lmyc.Models;
using Lmyc.Models.BookingViewModels;
using Microsoft.AspNetCore.Identity;
using Lmyc.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Lmyc.Controllers
{
    [Authorize(Policy="RequireLogin")]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookingsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bookings.Include(b => b.Boat).Include(b => b.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Boat)
                .Include(b => b.User)
                .Include(b => b.UserBookings)
                    .ThenInclude(b => b.User)
                .OrderBy(b => b.StartDateTime)
                .SingleOrDefaultAsync(m => m.BookingId == id);

            if (booking == null)
            {
                return NotFound();
            }

            var userRoles = new List<UserRoleData>();

            foreach (var b in booking.UserBookings)
            {
                var userRole = new UserRoleData
                {
                    FisrtName = b.User.FirstName,
                    LastName = b.User.LastName,
                    UsedCredit = b.UsedCredit,
                    RoleName = string.Join(",", _userManager.GetRolesAsync(b.User).Result)
                };

                userRoles.Add(userRole);
            }

            var model = new BookingViewModel
            {
                BookingId = booking.BookingId,
                BoatId = booking.BoatId,
                BoatName = booking.Boat.BoatName,
                StartDateTime = booking.StartDateTime,
                EndDateTime = booking.EndDateTime,
                NonMemberCrews = booking.NonMemberCrews,
                Itinerary = booking.Itinerary,
                AllocatedHours = booking.AllocatedHours,
                UserId = booking.UserId,
                MemberCrews = userRoles
            };

            return View(model);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            var booking = new Booking
            {
                UserBookings = new List<UserBooking>()
            };
            PopulateBookingUserData(booking);
            ViewData["Boats"] = new SelectList(_context.Boats, "BoatId", "BoatName");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoatId,StartDateTime,EndDateTime,AllocatedHours,NonMemberCrews,Itinerary")]Booking booking, string[] memberCrews)
        {
            if (memberCrews != null)
            {
                booking.UserBookings = new List<UserBooking>();
            }

            foreach (var user in memberCrews)
            {
                var BookingToAdd = new UserBooking
                {
                    BookingId = booking.BookingId,
                    UserId = user
                };

                booking.UserBookings.Add(BookingToAdd);
            }

            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                booking.UserId = user.Id;
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            PopulateBookingUserData(booking);
            ViewData["Boats"] = new SelectList(_context.Boats, "BoatId", "BoatName", booking.BoatId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.SingleOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            ViewData["BoatId"] = new SelectList(_context.Boats, "BoatId", "BoatName", booking.BoatId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,StartDateTime,EndDateTime,NonMemberCrew,Itinerary,AllocatedHours,UserId,BoatId")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoatId"] = new SelectList(_context.Boats, "BoatId", "BoatName", booking.BoatId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Boat)
                .Include(b => b.User)
                .Include(b => b.UserBookings)
                    .ThenInclude(b => b.User)
                .OrderBy(b => b.StartDateTime)
                .SingleOrDefaultAsync(m => m.BookingId == id);

            if (booking == null)
            {
                return NotFound();
            }

            var userRoles = new List<UserRoleData>();

            foreach (var b in booking.UserBookings)
            {
                var userRole = new UserRoleData
                {
                    FisrtName = b.User.FirstName,
                    LastName = b.User.LastName,
                    UsedCredit = b.UsedCredit,
                    RoleName = string.Join(",", _userManager.GetRolesAsync(b.User).Result)
                };

                userRoles.Add(userRole);
            }

            var model = new BookingViewModel
            {
                BookingId = booking.BookingId,
                BoatId = booking.BoatId,
                BoatName = booking.Boat.BoatName,
                StartDateTime = booking.StartDateTime,
                EndDateTime = booking.EndDateTime,
                NonMemberCrews = booking.NonMemberCrews,
                Itinerary = booking.Itinerary,
                AllocatedHours = booking.AllocatedHours,
                UserId = booking.UserId,
                MemberCrews = userRoles
            };

            return View(model);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings
                .Include(b => b.UserBookings)
                    .ThenInclude(b => b.User)
                .SingleOrDefaultAsync(b => b.BookingId == id);
            //var booking = await _context.Bookings.SingleOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            foreach (var b in booking.UserBookings)
            {
                // return the credit
                b.User.CreditBalance += b.UsedCredit;
            }

            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingId == id);
        }

        private void PopulateBookingUserData(Booking booking)
        {
            var users = _context.Users;
            var userBookings = new HashSet<string>(booking.UserBookings.Select(u => u.UserId));
            var model = new List<BookingUserData>();
            
            foreach (var user in users)
            {
                model.Add(new BookingUserData
                {
                    UserId = user.Id,

Lmyc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lmyc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/main.css" />*@
        <link rel="stylesheet" href="~/css/main.css" />
        @*checkbox*@
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>
</head>
<body>
    <!-- Header -->
    <header id="header">
        <div class="inner">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo">LMYC</a>

            <nav id="nav">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                <a asp-area="" asp-controller="Boats" asp-action="index">Boats</a>
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-area="" asp-controller="Bookings" asp-action="index">Bookings</a>
                    <a asp-area="" asp-controller="Volunteers" asp-action="index">Volunteers</a>
                    <a asp-area="" asp-controller="Documents" asp-action="index">Documents</a>
                    <a asp-area="" asp-controller="Swagger" asp-action="Index">API Information</a>
                }
                @await Html.PartialAsync("_LoginPartial")
            </nav>
            <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
        </div>
    </header>

    <!-- Banner -->
    @*<section id="banner">
        <h1>Welcome to LMYC</h1>
        <p>Lower Mainland Yacht Co-Op</p>
    </section>*@

    <!-- One -->

    <section id="three" class="wrapper special">
        <div class="inner">
            <header class="align-center">
                @RenderBody()
            </header>
            <div class="flex flex-2">
                <article>
                    @RenderBody()
                </article>
            </div>
        </div>
    </section>


    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <div class="flex">
                <div class="copyright">
                    <p>&copy; 2018 - Lmyc</p>
                </div>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/skel.min.js"></script>
        <script src="~/js/util.js"></script>
        <script src="~/js/main.js"></script>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
      

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>